default: &default
  adapter: postgresql

development:
  <<: *default
  database: birdseed_dev

test:
  <<: *default
  database: birdseed_test

production:
    <<: *default
    encoding: unicode
    database: <%= ENV['RDS_DB_NAME'] %>
    username: <%= ENV['RDS_USERNAME'] %>
    password: <%= ENV['RDS_PASSWORD'] %>
    host: <%= ENV['RDS_HOSTNAME'] %>
    port: <%= ENV['RDS_PORT'] %>
